.TH "TSV2OSIS-FORMAT" 7 "2019-05-19" "tsv2osis.awk" "OSIS TOOLS"
.SH NAME
tsv2osis \- input format description
.SH DESCRIPTION
.PP
The following table describes the format.
.TS
tab(|);
| l | l | l | l | l |.
=
ID | Text | Alternatives | References | Notes
=
Matt.1.1 | The Revelation of Jesus |
| Christ, which God gave him |
| to show unto his |
| servants, | bondservants |
| even the things | gave unto him, to ... |
| which must shortly come |
| to pass: and he |
| sent and signified it | them |
| by his angel unto |
| his servant John; |
Matt.1.2 | who bare witness |
| ...
=
.TE
.SH SEE ALSO
.BR tsv2osis (1)
