.TH "TSV2OSIS.AWK" 1 "2019-05-19" "tsv2osis.awk" "OSIS TOOLS"
.SH NAME
tsv2osis.awk \- convert formatted tsv to osis xml format.
.SH SYNOPSIS
.BR tsv2osis.awk " <"
.IR source.tsv " > " osis-part.xml
.SH DESCRIPTION
.PP
This program outputs the corresponding paragraph/verse format for
.I osis
bibles.
.SH SEE ALSO
.BR tsv2osis (7)
